name: Telegram Bot Action

# 파일이 실행 되는 조건
# 현재 기준 main branch 에 코드가 push 되는 조건을 가지고 있음
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name : Telegram Bot Action
    runs-on : ubuntu-latest
    steps:
      - name : Checkout Branch
        uses : actions/checkout@v3

      - name : Docker Login
        uses : docker/login-action@v2.0.0
        with :
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name : Generate ENV File
        env:
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run : |
          echo "TELEGRAM_API_KEY=$TELEGRAM_API_KEY" >> env.dev
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> env.dev


      - name : Build and Push Docker Images
        uses : docker/build-push-action@v3.0.0
        with :
          context: .
          file : ./Dockerfile
          push : true
          platforms: linux/amd64
          tags : tjehdgur1500/telegram-bot-gcp
          labels: latest

      - id : "auth"
        name : Authenticate to GCP
        uses : google-github-actions/auth@v2
        with :
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name : SSH into GCP VM and Deploy
        uses : appleboy/ssh-action@master
        with :
          host : ${{ secrets.GCP_VM_HOST }}
          username : ${{ secrets.GCP_VM_NAME }}
          key : ${{ secrets.GCP_SSH_KEY }}
          port : ${{ secrets.GCP_PORT }}
          script : |
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q) && docker rmi tjehdgur1500/telegram-bot-gcp:latest
            docker pull tjehdgur1500/telegram-bot-gcp:latest
            docker run -d -p 8000:8000 -v /etc/localtime:/etc/localtime:ro -e TZ=Asia/Seoul tjehdgur1500/telegram-bot-gcp:latest